"""Acceptance model for speculative decoding.

A draft token is accepted iff a random draw passes the per-position
acceptance rate. The rate is measured end-to-end on a real speculator, so
it already encodes both draft correctness and target verification — there
is no separate token-match check. First failure breaks the chain: all
subsequent draft tokens in the step are rejected.
"""

from __future__ import annotations

import random

from simulator.config.simulator_config import SpeculativeDecodeConfig
from simulator.core.request_state import SimRequestState


class AcceptanceModel:
    """Models token acceptance in speculative decoding.

    Usage::

        model = AcceptanceModel(config, seed=42)
        num_accepted, num_rejected, num_beyond = model.evaluate(request, draft_tokens)

    A single RNG is shared across all requests and consumed in scheduling
    order, so results are reproducible for a fixed schedule but
    inter-request-coupled and order-dependent.
    """

    def __init__(self, config: SpeculativeDecodeConfig, seed: int = 42):
        self._config = config
        self._rng = random.Random(seed)
        if config.accept_mode == "per_position" and config.acceptance_rates:
            if len(config.acceptance_rates) < config.num_spec_tokens:
                raise ValueError(
                    f"acceptance_rates has {len(config.acceptance_rates)} entries "
                    f"but num_spec_tokens={config.num_spec_tokens}. "
                    f"Provide at least {config.num_spec_tokens} rates "
                    f"(one per draft position)."
                )

    def evaluate(
        self, req: SimRequestState, draft_tokens: list[int]
    ) -> tuple[int, int, int]:
        """Evaluate K draft tokens against the per-position acceptance rates.

        Args:
            req: Request state with ``ground_truth_output``.
            draft_tokens: K draft tokens proposed for this decode step. Only
                the length is used (drafts are assumed to be ground truth,
                generated by SpeculativeDecodeEngine); acceptance is decided
                purely by the rate.

        Returns:
            (num_accepted, num_rejected, num_beyond_ground_truth).
            - num_accepted: drafts that passed the rate draw.
            - num_rejected: drafts that failed the rate draw before the chain
              broke. These are the meaningful rejections for acceptance-rate
              metrics.
            - num_beyond_ground_truth: drafts that could not be evaluated
              because they fall past the end of ground truth. NOT real
              rejections — the sequence simply ended — so excluded from
              acceptance-rate metrics. The caller still frees their slots
              (num_accepted + num_rejected + num_beyond == K).

            The bonus (position 0) is NOT counted here — the caller handles
            the bonus separately.
        """
        K = len(draft_tokens)
        if K == 0:
            return 0, 0, 0

        output_position = len(req.output_token_ids)
        num_accepted = 0
        beyond_ground_truth = 0

        for i in range(K):
            # +1 because the bonus token occupies output_position;
            # the first draft token is at output_position + 1
            abs_position = output_position + 1 + i

            # Beyond ground truth — cannot verify.  Not a rejection.
            if abs_position >= len(req.ground_truth_output):
                beyond_ground_truth = K - i
                break

            # Per-position acceptance-rate sampling. First miss breaks the
            # chain (subsequent drafts are rejected).
            accept_rate = self._get_accept_rate(i)
            if self._rng.random() >= accept_rate:
                break

            num_accepted += 1

        num_rejected = max(0, K - num_accepted - beyond_ground_truth)
        return num_accepted, num_rejected, beyond_ground_truth

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    def _get_accept_rate(self, position: int) -> float:
        if self._config.accept_mode == "fixed":
            return self._config.acceptance_rate
        elif self._config.accept_mode == "per_position":
            rates = self._config.acceptance_rates
            if rates:
                return rates[min(position, len(rates) - 1)]
            return 0.5
        return 0.8
